In [2]:
import pandas as pd
df = pd.DataFrame({
    'name': ['Ali', 'Zara', 'Jasur'],
    'age': [22, 28, 31],
    'city': ['Tashkent', 'Samarkand', 'Biukhara']
})
# When you select one column, pandas returns a Series
# When you select multiple columns using a list, pandas returns a DataFrame.

In [19]:
df = pd.read_csv('tip.csv', encoding='latin1')
parse_dates = ['your_date_col']
df.head()
# df.shape
# df.info()
# df.describe()
# df.isna().sum()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [24]:
df['total_bill']

df[['tip', 'sex']]

df.loc[4]

df.iloc[4]

total_bill     24.59
tip             3.61
sex           Female
smoker            No
day              Sun
time          Dinner
size               4
Name: 4, dtype: object

In [25]:
df[(df["total_bill"] > 20) & (df["tip"] == "3.0")]

Empty DataFrame
Columns: [total_bill, tip, sex, smoker, day, time, size]
Index: []

Why use & instead of and?

Because pandas works with Series (arrays), not single values.

and works only with True/False (single values)
& works element-wise (for all rows)

In [27]:
df.groupby('sex')['total_bill'].mean()

sex
Female    18.056897
Male      20.744076
Name: total_bill, dtype: float64

In [29]:
df.groupby('sex').agg({
    'tip': 'mean',
    'smoker': 'count'
})

             tip  smoker
sex
Female  2.833448      87
Male    3.089618     157

What type does the first call return?

A Series.
Because you selected one column ("age"), the result is a Series.

In [30]:
import pandas as pd

df = pd.DataFrame({
    "name": ["Ali", "Zara", "Jasur"],
    "city": ["Tashkent", "Samarqand", "Bukhara"]
})

lookup_df = pd.DataFrame({
    "city": ["Tashkent", "Samarqand"],
    "population": [2500000, 600000]
})

merged_df = pd.merge(df, lookup_df, on="city", how="left")
print(merged_df)

    name       city  population
0    Ali   Tashkent   2500000.0
1   Zara  Samarqand    600000.0
2  Jasur    Bukhara         NaN

Rows in the left table are always kept in the result. If there is no matching value in the lookup table, the new columns will contain NaN (missing values).